# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cogni < Formula
  desc "MCP server for AI coding agents — structured repo recall with 40-60% token reduction"
  homepage "https://getcogni.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_darwin_amd64.tar.gz"
      sha256 "5e7944cdaa22dfb2d5122f612079de7f2f46c566c6a46c7b9e3d26e8bb2335e5"

      define_method(:install) do
        bin.install "cogni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_darwin_arm64.tar.gz"
      sha256 "cc91968b01da061c8751368f18164c0a548fb4a7241b0c7e7c2b4601fd31667e"

      define_method(:install) do
        bin.install "cogni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_linux_amd64.tar.gz"
      sha256 "2157a0db9c549e6ba849b81b09ca4690a41be9c861f2661a8e30a41d962b8653"
      define_method(:install) do
        bin.install "cogni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_linux_arm64.tar.gz"
      sha256 "da4c1d62112010230dbf9dcf958ada268e62f19e2114517269558a029f813645"
      define_method(:install) do
        bin.install "cogni"
      end
    end
  end

  test do
    system "#{bin}/cogni", "--version"
  end
end
