# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cogni < Formula
  desc "MCP server for AI coding agents — structured repo recall with 40-60% token reduction"
  homepage "https://getcogni.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_darwin_amd64.tar.gz"
      sha256 "7b07d8ea86d5f38de7209c637a0446058e4a9b657138a2f6128339b4454be994"

      define_method(:install) do
        bin.install "cogni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_darwin_arm64.tar.gz"
      sha256 "1395b80e19e5728d2deb35bb2bbd7cbc44a056d7e75c56828ce65538e3db5e47"

      define_method(:install) do
        bin.install "cogni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_linux_amd64.tar.gz"
      sha256 "8f5020d689f96f28c11de807ae3c4e39a73b59f091d09b9ed7a54f6ab2f615bf"
      define_method(:install) do
        bin.install "cogni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/islamborghini/cogni/releases/download/v0.1.0/cogni_linux_arm64.tar.gz"
      sha256 "257812b9d12346361458b4edea454cdfcc9b57b2b0aa65ccf8b55ea6c298d0a3"
      define_method(:install) do
        bin.install "cogni"
      end
    end
  end

  test do
    system "#{bin}/cogni", "--version"
  end
end
